### ISSUE TITLE
Math blocks can break syntax highlighting

### ISSUE THREAD

**Issue by fonnesbeck** [textmate/markdown.tmbundle#46]
When specifying Markdown (MathJax) math blocks for writing equations, some equation characters will break the syntax highlighting for the file, making all of the text below the equation unhighlighted. This happens most frequently with equations that have underscores in them. Here is an example:

![](http://d.pr/i/FtjIH+)

If the offending equation is removed, the highlighting is restored:

![](http://d.pr/i/XTskk+)

Everything inside of double-dollar signs (`$$`) should be considered part of the equation.

**Comment by infininight** [comment]
Two things are at play here:

MathJax is not part of the markdown spec so excluding them from italics can't happen by default. This bundle only supports the base markdown, the MathJax bundle could add a math for the blocks and exclude italics inside them if desired.

The example provided does not happen with the grammar from this bundle, we require an ending to the italics exist on the same line. The grammar at fault here is in the Markdown (Github) bundle which is more permissive about where italics are allowed.

**Comment by noniq** [comment]
This might have been already fixed in the Github Markdown bundle, see https://github.com/MikeMcQuaid/GitHub-Markdown.tmbundle/pull/21

**Comment by fonnesbeck** [comment]
@noniq Thanks for that. I will check it out.

**Comment by infininight** [comment]
@fonnesbeck I had missed the @noniq pull request so my bundle was outdated and I hadn't deployed this change. However it did not actually solve the issue due to some interactions with the rule and the standard italics rule. I've made a new pull request at MikeMcQuaid/GitHub-Markdown.tmbundle#24 which contains some fixes and somewhat improves your use case. It will still match in an undesired fashion but will no longer extend outside the current line. It could also be confused by two MathJax strings on the same line but would still not persist the error past the line.

**Comment by fonnesbeck** [comment]
@infininight Thanks, I will test the new PR, which I see is already merged.
